### ISSUE TITLE
Machinist should not change srand value globally

### ISSUE THREAD

**Issue by adamsalter** [notahat/machinist#10]
I think it could probably be considered a security flaw since machinist doesn't reset the `srand` after use.

`srand` returns the current value when you call it, so you could do something like this:

```
start_machinist_srand = srand(machinist_srand_value)
...
some_stuff do; end
#machinist ready to return to application
srand(start_machinist_srand)
```

Thanks for a great blueprinting gem. ;)

**Comment by notahat** [comment]
Actually, srand returns the value that originally seeded the current sequence. The code you provide will reset the global sequence every time you run it.

Machinist re-seeds srand when it's done, which is about the best you can do if you want rand to behave sensibly.

I'm not sure how this qualifies as a security flaw. Care to elaborate?

**Comment by adamsalter** [comment]
Right.

I misunderstood the code. You're method is essentially making the best of a bad situation.

I saw it as a security flaw if you could predict what values rand would return after using  Sham.
