### ISSUE TITLE
Machinist2 and dirty tracking

### ISSUE THREAD

**Issue by papricek** [notahat/machinist#105]
Unfortunately, it seems that Machinist in cooperation with Active Record somehow bypasses dirty tracking. While I have test based on after_save callback, the tracked attribute must be set explicitely, otherwise tracked_changed? returns false... Is that machinists intended behavior?

```
# in after_save tracked_changed? returns false
client = Client.make!(:tracked => "AAA")


# in after_save tracked_changed? returns true
client = Client.make!
client.tracked = "XXX"
client.save
```

**Comment by notahat** [comment]
I just tried this, and it works correctly for me. You'll have to give me some runnable code that demonstrates the problem.
