### ISSUE TITLE
ActiveSupport dependency not declared in gemspec

### ISSUE THREAD

**Issue by mattsoutherden** [notahat/machinist#11]
sham.rb requires active_support, though this is not specified in the gemspec dependencies (and is not seemingly required).

**Comment by notahat** [comment]
You're right, it's not needed anymore. I've taken the require out.

(GitHub isn't building gems at the moment, so a gem update will have to wait.)

Thanks for the report.

**Comment by mattsoutherden** [comment]
Perhaps I was a bit premature. 'returning' is used in machinst.rb:16, which comes from activesupport. I guess it depends on how much you like that idiom as to whether it's worth having the dep or not. (I'm using machinist/object in the project I noticed this).
