### ISSUE TITLE
Blueprint file not found when using Capybara and spec

### ISSUE THREAD

**Issue by rtacconi** [notahat/machinist#114]
I get this

```
 Failure/Error: @user = User.make!
 Machinist::NoBlueprintError:
   No master blueprint defined for class User
```

When I run the files in /spec/requests. Everything is okay under spec/models and spec/controllers. I am getting mad, I tried everything. this is the spec_helper.rb. Please HELP

require 'spork'
require 'capybara/rspec'
require 'machinist'

Spork.prefork do  
  ENV["RAILS_ENV"] ||= 'test'
  require File.expand_path("../../config/environment", **FILE**)
  require 'rspec/rails'

  Dir[Rails.root.join("spec/support/*_/_.rb")].each {|f| require f}

  require 'cover_me'

  RSpec.configure do |config|
    config.mock_with :rspec

```
config.before(:each) do
  Timecop.return
  FakeWeb.clean_registry
end

config.include Devise::TestHelpers, :type => :controller

config.use_transactional_fixtures = true

config.before do
  Capybara.current_driver = Capybara.javascript_driver if example.metadata[:js]
  Capybara.current_driver = example.metadata[:driver] if example.metadata[:driver]
end

config.after do
  Capybara.use_default_driver
end

config.use_transactional_fixtures = false

config.before(:suite) do
  DatabaseCleaner.strategy = :truncation
end

config.before(:each) do
  DatabaseCleaner.start
end

config.after(:each) do
  DatabaseCleaner.clean
end
```

  end

  Capybara.javascript_driver = :webkit

  Capybara::Driver::Webkit::Browser.class_eval do 
    def forward_stdout(pipe); end;
  end
end

Spork.each_run do 
  Dir[Rails.root.join("spec/support/**/*.rb")].each {|f| require f} 
  DatabaseCleaner.clean
  Dir[Rails.root.join("app/models/**/*.rb")].each {|f| load f}
end

def get_image
  @image = File.new(Rails.root.to_s+"/spec/support/alex.gif") if @image.nil?

  @image
end

**Comment by rtacconi** [comment]
Please help I am stuck

**Comment by rtacconi** [comment]
I upgraded to rails 3.2 (from 3.1) and the error is gone

**Comment by Jimflip** [comment]
don't see how that fixes the problem?
I'm on rails 3.1 and it doesn't work, upgrading to rails 3.2 isn't a feasible option at the moment.
