### ISSUE TITLE
Validation errors should be shown

### ISSUE THREAD

**Issue by jeroenvandijk** [notahat/machinist#13]
When #make fails due to validation errors it is not immediately clear which attributes need to be added or changed.

For ActiveRecord I have applied the following hack to get it working:

```
class ActiveRecord::Base
  class << self
    def make_with_error_presentation(*args, &block)
      make_without_error_presentation(*args, &block)
    rescue ActiveRecord::RecordInvalid => invalid
      raise "#{invalid.message}. The following errors were found: #{invalid.record.errors.full_messages} for #{invalid.record.class.name}"
    end
    alias_method_chain :make, :error_presentation
  end
end
```

I could supply a patch to get this into machinist if you are interested.

**Comment by notahat** [comment]
Good idea. Want to do a non-hacked version that I can merge?

**Comment by jeroenvandijk** [comment]
Sure. I will focus on the ActiveRecord version, because I'm less familiar with DataMapper. Expect a pull request in the next couple of days.

**Comment by jeroenvandijk** [comment]
I just wrote a spec to drive my implementation and guess what ActiveRecord already gives a good error message out of the box.

It was just that I hadn't defined a I18n key yet. And ActiveRecord actually gave me a good hint which I apparently just ignored:

```
  translation missing: nl, activerecord, errors, messages, record_invalid
```

By default this translation is :  
   record_invalid: "Validation failed: {{errors}}"

So I think this patch would be unnecessary :)

**Comment by notahat** [comment]
Fair enough. Issue closed!
