### ISSUE TITLE
Latest gem only has lib folder

### ISSUE THREAD

**Issue by drnic** [notahat/machinist#14]
There are no Rakefile, README, test/spec folder in the 1.0.5 bundled gem

**Comment by notahat** [comment]
I thought not including these was a feature! Is there a compelling reason to put these in the gem?

**Comment by drnic** [comment]
Heh, maybe :)

I use http://github.com/adamsanderson/open_gem to view gem source, rather than figure out the gem's source, download/clone it, etc. So "gem open machinist" was the command I ran to discover no tests/docco etc.

Another way people can get a project's source and run its tests is "gem unpack machinist".

So +1 for full source in a .gem from me :)

**Comment by notahat** [comment]
You've sold me. I'll fix it when I get a spare moment.

**Comment by drnic** [comment]
At least it sort of prompted me to add "gh clone --search" to the github-gem project :) http://drnicwilliams.com/2009/11/04/hacking-someones-gem-with-github-and-gemcutter/

**Comment by notahat** [comment]
Done. Using Jeweler for releases now.
