### ISSUE TITLE
provide attribute generators with an index parameter

### ISSUE THREAD

**Issue by bigfix** [notahat/machinist#15]
Often I want to define a quick indexed generator that's specific to a particular model and attribute. It would be nice if I could use this syntax:

```
Post.blueprint do
  title {|index| "Post #{index}"}
end
```

Sometimes moving an indexed generator like this into a named Sham is a good thing, but in other cases it just impairs readability and pollutes the Sham namespace.

**Comment by notahat** [comment]
Sounds like a good idea to me. Feel like forking and giving it a go?

You'd have to find somewhere to store each index, and have a hook to reset them before each test much the way Sham does.

**Comment by jeremydurham** [comment]
I added this on my fork of Machinist with specs: jeremydurham/machinist@35a38d9715caf52cb33a6e73c65e0391c8c95bff

**Comment by jfirebaugh** [comment]
Thanks Jeremy, that's what I'm looking for.

One nit: index should probably match Sham and start with 1 rather than 0.

**Comment by jeremydurham** [comment]
Good call; I wondered about this but didn't take the time to look and see what Sham does. Updated: jeremydurham/machinist@a52de812478265301726dad00c91af66de8b2656

**Comment by jfirebaugh** [comment]
+1 to jeremydurham's changes. I've been using them and they work great.

**Comment by notahat** [comment]
Ok, finally cleaning up these old tickets!

I think this is a great idea, but I've found people are already confused by Sham and indexing, and having indexes in another place as well would just add to the confusion.

I'm preparing a pre-release of Machinist 2, and the road I've gone down there (for a bunch of reasons) is to throw out Sham, and do everything with indexes in blueprints.

So, in short, your idea wins, and my original idea is going out the window. I'll add you to the list of contributors to Machinist 2, Jeremy. Thanks for the discussion and the work!
