### ISSUE TITLE
Setting id inside a blueprint doesn't work for me.

### ISSUE THREAD

**Issue by leandro** [notahat/machinist#16]
Since my model doesn't have a typical primary_key I have to set id by hand, and it has to take a MD5 string hash. But when I try to set it via blueprint it doesn't work.

Maybe this has to do with this line inside the lib/machinist.rb:
undef_method :id   if respond_to?(:id)

Right?

**Comment by notahat** [comment]
That line is there so that you can set id in a blueprint.

Can you give me some code to run that demonstrates that problem?

**Comment by leandro** [comment]
So, I was building a rails app to reproduce the problem and turns out that the problem was related to my custom :id field not accepting a null value via migration (with the :null => false in the options). So if my "save!" method inside the standard "make" method from Machinist gem failed the folowing "reload" method would fail as well, since Active Record fills such field with 0 (zero) on it, when saving fails.

**Comment by notahat** [comment]
Ok, so sounds like it wasn't directly Machinist related. I'll close the issue...re-open it if you think there's a relevant change to Machinist.

**Comment by leandro** [comment]
Yup, no problem. I'll keep an eye on the problem if it happens again from outside that my previous situation.
