### ISSUE TITLE
setting a value called "format" doesn't work

### ISSUE THREAD

**Issue by swoker** [notahat/machinist#18]
Hi

First of all I want to tell you that your plugin is great and simplifies my testing environment heavily, but unfortunately I've got a problem that I cannot set a value with the name "format" in my blueprints.

My Example looks like this:
class Example < ActiveRecord::Base
  validates_presence_of :name
  validates_presence_of :format
end

My Blueprint: 
Example.blueprint do
  name             Sham.name
  format            Sham.format # also tried 'test' and different Sham-functions here
end

If I call "Example.make" now, I get an error "Validation failed: Format can't be blank".
But if I call "Example.make :format => 'test' " it works fine without any issues.

I've tried it with several classes now. Everything I tried worked fine, but "format" never did.

Any clues what the problem could be?
I also use the Forgery-Gem. Is it possible that this causes the issues?

Kind regards
Simon

**Comment by jeremydurham** [comment]
Unfortunately, format and test are defined on Kernel in Ruby (and mixed into Object), and because of the way instance_eval works, the one way to solve this issue is to do:

```
Example.blueprint do
  name Sham.name
  self.format Sham.format
end
```

Hope that helps,
Jeremy

**Comment by swoker** [comment]
Yeah, that was the issue. 
Thanks a lot!

**Comment by notahat** [comment]
Yep, that's it.

Also:

```
name Sham.name
```

will break in unexpected ways. You must put attribute values in blueprints inside blocks:

```
name { Sham.name }
```

You can also reduce this to just:

```
name
```

Machinist will automatically look for a matching Sham definition.

**Comment by pwoestelandt** [comment]
Hi,

I have a similar issue with an other attribute name called "controller".

But the solution doesn't work:

> self.controller { 'catalog_list' }

This issue appeared after updating 2.3.5 to 2.3.12

For the moment I use MyBlueprint.make(:controller => 'catalog_list')

Thanks in advance.
Paul
