### ISSUE TITLE
Sham interferes with Mocha?

### ISSUE THREAD

**Issue by vidmantas** [notahat/machinist#19]
Hi, 

I've tried to use mocha with machinist in one project and got the following problem:
http://pastie.org/761613

the line that invokes this error is just a:
@user_session = mock

I've required machinist as a gem in my test environment file as well as mocha: 
config.gem 'machinist', :lib => "machinist", :version => "~> 1.0.6"
config.gem "mocha", :lib => false, :version => '~> 0.9.8'

**Comment by vidmantas** [comment]
Sorry, totally my mistake. Didn't notice that one method defined in spec_helper has the same name as one of Sham objects!

**Comment by notahat** [comment]
Ok, closing the issue.
