### ISSUE TITLE
Does Machinist support has_many through relationships.

### ISSUE THREAD

**Issue by powertoaster** [notahat/machinist#20]
I have just switched from factory_girl to machinist and I am having trouble with a hmt relationship.

Employee.blueprint do
  username
  password {'password'}
  password_confirmation {'password'}
  tms_code
  first_name
  last_name
  active false
  role
  timesheet
end

Role.blueprint do
  description
  employee
end

I get RuntimeError: No sham defined for role

What am I doing wrong here? Or is it just not supported yet?

**Comment by powertoaster** [comment]
Sorry, I guess I did not read this well enough. I need to create them through a helper and not have them in the blueprint at all.

**Comment by powertoaster** [comment]
Done

**Comment by notahat** [comment]
Yep, a helper is the way to go.

FactoryGirl's approach to these can cause all sorts of problems where an Employee creates a Role that creates an Employee, etc. Unfortunately ActiveRecord makes it really hard to work around this issue, so I've just discouraged people from creating objects through anything other than belongs_to relationships using Machinist.

One day I'll dream up a better solution.

**Comment by lancecarlson** [comment]
I think a work around would be adding support for blueprint callbacks. Something like this would be cool:

User.blueprint do
  before :save
  end

  after :save
    posts << Post.make
  end
end

**Comment by notahat** [comment]
I don't see how this would help, Lance. If the Post blueprint creates a User, you still have an infinite loop. Creating the Post a bit later doesn't make a difference, does it?
