### ISSUE TITLE
List additional development dependencies

### ISSUE THREAD

**Issue by TylerRick** [notahat/machinist#21]
Please consider adding these:
    gem.add_development_dependency "activerecord"
    gem.add_development_dependency "sequel"
    gem.add_development_dependency "dm-core"
    gem.add_development_dependency "dm-validations"
    gem.add_development_dependency "data_objects"
    gem.add_development_dependency "do_sqlite3"

rake spec was giving ugly errors until I installed all of those.

**Comment by notahat** [comment]
Added development dependencies for ActiveRecord, DataMapper, etc.

Closed by ab33eaf641a06b78adc12d662d6babc4f5de629e.
