### ISSUE TITLE
Sham: Add an option to seed srand with something other than 1

### ISSUE THREAD

**Issue by TylerRick** [notahat/machinist#22]
Sometimes I might just want to let srand do its default behavior (If _number_ is omitted or zero, seeds the generator using a combination of the time, the process id, and a sequence number.) and see if the tests still pass.

Or I might just get tired of seeing the same names come up again and again in the tests.

What's the point of having so many possible values that Sham/Faker might yield if I only over see the first several?

**Comment by TylerRick** [comment]
Or... Couldn't we just instruct the user to put an srand(1) in their tests if they want reproducibility and leave it out if they'd prefer randomness?

**Comment by notahat** [comment]
The point is that you have the same data every time you run your tests. Having different data on each run is a terrible idea, because it means you can't isolate failures.

**Comment by TylerRick** [comment]
Regarding the randomness idea, I guess I was just thinking something along the same lines as Heckle: "The idea is that if your specs still pass after the code has been mutated, then your specs are incomplete, and RSpec will tell you."

It seems highly unlikely that an example would pass with one value generated from Faker/Sham and fail with another random value generated by the same generator method. And if it did fail, then something is wrong with your code or your value generator.

But you're right, it would be confusing to try to isolate failures. How does Heckle solve that problem? (I admit I haven't even used Heckle before)

**Comment by TylerRick** [comment]
But my other reason for wanting to change the seed was not to create randomness but variety.

I thought to myself, why should "Kunde-Smith" and "Lake Aricfurt" get all the fame and glory?

Anytime anyone uses Machinist with Faker and asks for a company name or a city, they are going to get "Kunde-Smith" and "Lake Aricfurt", respectively. Whereas if Faker were used on its own you would most likely see something completely different, like "Mayer and Sons", "Anderson-Prohaska", "Wintheiser, Dickinson and Lehner".

It just seems kind of ... boring that all Machinist-Faker-powered specs everywhere will end up with "Kunde-Smith" as their company name. Probably not big enough of a problem to bother most people, but then again, forcing a seed of 1 on anyone seems a little close-minded... that's all I'm saying :)
