### ISSUE TITLE
Autoloading of blueprints and adapters

### ISSUE THREAD

**Issue by fox** [notahat/machinist#26]
I've create a branch at http://github.com/fox/machinist/tree/autoloading that adds two related features:
- Blueprints gets automatically loaded from the following locations 
  
  test/blueprints.rb
  spec/blueprints.rb
  test/blueprints/_.rb
  spec/blueprints/_.rb
- ORM adapters get automatically loaded. This works only when the ORM library ('active_record' ) is required before requiring machinist.

Pull if you like!

**Comment by fox** [comment]
It's been ages since I've posted this, anyone found this useful? Autoloading of blueprints is a feature of object_daddy and factory_girl, poeple might like that in machinist too.

**Comment by notahat** [comment]
Thanks for the patch, but I'm not a fan of autoloading magic in general, particularly when it's dependent on load order.

Machinist 2, which will get a pre-release soon, comes with proper generators for Rails 3, which means you won't have to think about this stuff for Rails projects anyway.
