### ISSUE TITLE
generate_attribute_value cases problems with polymorphic associations

### ISSUE THREAD

**Issue by adevadeh** [notahat/machinist#27]
everything was fine with notahat-machinist 1.0.3 from github. When updating to gemcutter 1.0.6, we ran into an issue with our polymorphic associations.

The issue is here:

def generate_attribute_value(attribute, *args)
      if block_given?
        # If we've got a block, use that to generate the value.
        yield
      else
        # Otherwise, look for an association or a sham.
        if @adapter.has_association?(object, attribute)
          @adapter.class_for_association(object, attribute).make(args.first || {})
        elsif args.empty?
          Sham.send(attribute)
        else
          # If we've got a constant, just use that.
          args.first
        end
      end
    end

```
    if @adapter.has_association?(object, attribute)
      @adapter.class_for_association(object, attribute).make(args.first || {})
```

An arg exists, but the association is polymorphic, meaning that class_for_association is unreliable. In our case, it returns a Module whish is not an Active Record object, and thus does not have the monkey-patched #make method.

The previous version treated the argument like a constant, which is exactly how we were using it.

Currently, the code seems to want to do to many things at once. I think we need to assume that associations without args should build an association, but associations with args can be treated as they were before.

**Comment by notahat** [comment]
Can you give me some example code that demonstrates the problem, preferably in the form of a failing test? I'm not sure I followed all that.

**Comment by kudelabs** [comment]
yeah, sorry. I just wanted to get something down before i forgot. i'll try to create a failing test.

**Comment by notahat** [comment]
Haven't heard anything back, so I'm closing this. I'll re-open if I can reproduce it.
