### ISSUE TITLE
nested blueprint classes don't inherit boolean values

### ISSUE THREAD

**Issue by jfrankov** [notahat/machinist#28]
I have a class structure in my rails app like this:

C > B > A

My blueprints file is like this:

A.blueprint do
  a_string { "foo" }
  a_boolean { true }
end

B.blueprint do
  A
end

C.blueprint do
  B
end

...so the values for a_string and a_boolean should show up when I do a C.make. But they don't. a_boolean keeps coming up blank in C. It work properly when I paste "a_boolean { true }" inside the blueprint for C but that's not DRY.

**Comment by notahat** [comment]
I can't reproduce this. If you can give me some runnable code that demonstrates the problem, I'll re-open the ticket.
