### ISSUE TITLE
How to test controllers using machinist

### ISSUE THREAD

**Issue by anilbhat** [notahat/machinist#29]
After reading the doc on github, I was able to do unit testing on my Rails application something like this in blueprints.rb file and then running respective files under test/unit directory:
Sham.define do
  url { Faker::Internet.domain_name }
  username { Faker::Internet.user_name }
  name  { Faker::Name.name }
end

Email.blueprint do
  name 
  url
  username
end

But when I try for functional testing, it gives errors in the following part of the code which is written in products_controller_test.rb file (I have products section in my application):
test "should create product" do
    assert_difference('Product.count') do
      post :create, :product => {:name => 'product_name', :description => 'test_description'}
    end
    assert_redirected_to product_path(assigns(:product))
  end

Any ideas would be appreciated...

**Comment by notahat** [comment]
I can't help you without the specific errors, and the code in your assert_difference block doesn't call Machinist at all. Please provide more info, and take your question to the mailing list.
