### ISSUE TITLE
Lack of Encoding Awareness (Reopened)

### ISSUE THREAD

**Issue by leehambley** [notahat/machinist#31]
I seem to have discovered a lack of encoding awareness.

Given the following environment
• Ruby 1.9.1 p378
• Rails Edge ( 3.0 b3 + @ SHA: 19cecc90 )

I see the following behavior:

<pre>
ruby-1.9.1-p378 > Player.make(:name => "Peter Jöback").name.encoding
 => # Encoding:ASCII-8BIT
ruby-1.9.1-p378 > Player.new(:name => "Peter Jöback").name.encoding
 => # Encoding:UTF-8
</pre>

(reopened because Github keyboard shortcuts pwned me.)

**Comment by notahat** [comment]
Can you try this and see what happens? (I don't have 1.9 on my box.)

```
player = Player.new(:name => "Peter Jöback")
player.save!
player.reload
player.name.encoding
```

That's the equivalent of what Machinist does under the hood.

**Comment by leehambley** [comment]
thanks for the tip, that blows up. with the reload it reverts to ascii-8bit. Is this possibly an upstream error in ActiveRecord?

**Comment by leehambley** [comment]
<pre>

1) Player should be encoding aware
    Failure/Error: player.name.encoding.should == Encoding.find('UTF-8')
    expected: #<Encoding:UTF-8>,
         got: #<Encoding:ASCII-8BIT> (using ==)
    # ./spec/models/player_spec.rb:19:in `block (2 levels) in <top (required)>'
##########
  it "should be encoding aware" do
    player = Player.new(:given_name => "Peter", :surname => "Jöback")
    player.name.encoding.should == Encoding.find('UTF-8')
    player.save!
    player.reload
    player.name.encoding.should == Encoding.find('UTF-8')
  end
</pre>

**Comment by notahat** [comment]
Definitely an issue with ActiveRecord, 1.9, and string encodings. Could even be related to database settings. Either way, it's not something I'm going to try to detect and work around in Machinist, so I'm closing the ticket.

**Comment by clemens** [comment]
For the record: This doesn't happen when using the mysql2 instead of the mysql gem. See http://stackoverflow.com/questions/3188740/activerecord-returns-data-in-ascii-8bit-under-ruby-1-9-2-rc1.
