### ISSUE TITLE
Machinist.with_save_nerfed doesn't restore old value

### ISSUE THREAD

**Issue by jfirebaugh** [notahat/machinist#32]
It resets @@nerfed to false even if it was already true. This causes the following to fail:

```
    Post.blueprint { }
    Comment.blueprint { }
    Comment.blueprint(:with_unvalidated_post) do
      post { Post.make_unsaved {|p| p.save(false)} }
    end
    Comment.make_unsaved(:with_unvalidated_post).should be_new_record
```

**Comment by fosrias** [comment]
I submitted a patch for this here:

http://github.com/fosrias/machinist

 but it has not been applied. I am not sure if Pete got it or not. In the meantime, the following in machinist.rb fixes this issue:

def self.with_save_nerfed
    prior_nerfed = @@nerfed
    begin
       @@nerfed = true
       yield
    ensure
       @@nerfed = prior_nerfed
    end
end

**Comment by notahat** [comment]
I've finally added this to the 1.0 branch, so it'll be in the next 1.0 maintenance release. Thanks for the patch.
