### ISSUE TITLE
blueprints should work for subclasses

### ISSUE THREAD

**Issue by danp** [notahat/machinist#33]
Consider:

Foo.blueprint do
  greeting "hello"
end

class Bar < Foo
...
end

Bar.make should work using blueprint defined on Foo.

**Comment by notahat** [comment]
It does, and there's a spec to prove it. See spec/machinist_spec.rb:169

You have to define an empty blueprint on Bar. Machinist enforces not letting you make a class unless you've explicitly blueprinted it.
