### ISSUE TITLE
Caching fails if transactional fixtures are off

### ISSUE THREAD

**Issue by notahat** [notahat/machinist#34]
Caching depends on transactional fixtures. If they're off, you may get objects back from make! that have been modified by earlier tests.

Caching should detect transactional fixtures and disable itself (possibly with a warning.)

**Comment by inspire22** [comment]
how do we even turn transactional fixtures on/off?  I've been using databasecleaner via rspec to handle it for me...

**Comment by sobrinho** [comment]
I sent a pull request. Waiting for pull.

**Comment by sobrinho** [comment]
Object caching was removed, this issue can be closed @notahat ;)

**Comment by notahat** [comment]
What sobrinho said.
