### ISSUE TITLE
Method "make" works not properly for objects with overloaded "initialize" method

### ISSUE THREAD

**Issue by DimaSamodurov** [notahat/machinist#35]
Let we have a class like:

<pre>
class User < ActiveRecord::Base
  def initialize(*args)
    super(*args)
    do_something_args_related(*args)  # this code won't run properly if we use User.make in tests, because make instantiates object without args passed and assigns parameters later.
  end
end
</pre>

This is a design issue and happens rarely. Do you think it's worth/possible to rewrite object instantiation and parameter assignment logic? I could try to do this but would like to get an advise first.

**Comment by notahat** [comment]
No, I wouldn't encourage this change. It would break a lot of existing users' test suites.

I'm working in this sort of thing in the strategies branch of Machinist 2, but it's still a while away from a release.

**Comment by DimaSamodurov** [comment]
Ok, making this change in a new version makes sense. We have a workaround now. Thanks!
