### ISSUE TITLE
set_primary_key in ActiveRecord models is not supported?

### ISSUE THREAD

**Issue by ened** [notahat/machinist#36]
Almost all of my classes use _id as primary key. So we write:

```
class Category < ActiveRecord::Base
  set_primary_key '_id'
```

That will break the Machinist sometimes. It broke the Category model, another model is fine.

```
class Device < ActiveRecord::Base
  set_primary_key '_id'
```

So for Category I have to use:
    Category.blueprint do
      title
      parent_category_id { nil }
      _id { 2 } # not yet randomized, I know..
    end

Is that a known issue?

**Comment by notahat** [comment]
Broke how? My quick manual test of non-id primary keys works just fine. Can you give me some code I can run that demonstrates a failure?

**Comment by ened** [comment]
Hi:

With the code above, the Category functional test fails:
    1) Error:
    test_should_destroy_category(CategoriesControllerTest):
    ActiveRecord::RecordNotFound: Couldn't find Category with ID=27
    machinist (1.0.6) lib/machinist/active_record.rb:56:in `make'
    /test/functional/categories_controller_test.rb:55:in`test_should_destroy_category'

Once I add the _id { 2 } thing it works.

**Comment by notahat** [comment]
That still isn't enough info for me to reproduce the problem. Can you pull the code that doesn't work out into a separate little project, tar it up, and send me a copy, so I can actually run it?

The line in Machinist that's failing is simply doing a reload on your model, which makes me think something else is wrong with your model.

**Comment by notahat** [comment]
Haven't heard anything back, so I'm closing this. I'll re-open it if I can reproduce it.

**Comment by keithpitty** [comment]
For the record, I encountered a similar problem and resolved it by removing the unused id column that was left over from before the primary key was changed.
