### ISSUE TITLE
Object caching fails under Ruby 1.8.6

### ISSUE THREAD

**Issue by notahat** [notahat/machinist#37]
There are a bunch of spec failures related to the shop when running under 1.8.6.

**Comment by notahat** [comment]
This is because hashes don't work properly as hash keys in 1.8.6. See:

http://paulbarry.com/articles/2009/09/14/why-rails-3-will-require-ruby-1-8-7

I'll have to manually hash the attributes when they're used as keys in the Warehouse.

**Comment by sobrinho** [comment]
Again, object caching was removed :P

**Comment by notahat** [comment]
What sobrinho said.
