### ISSUE TITLE
Need a Sham.reset(:all) and Sham.reset(:before)

### ISSUE THREAD

**Issue by lawrencepit** [notahat/machinist#4]
Hi Peter,

After railscamp05 I decided to have a go at a gem that allows easy object graph creation. I've named it Machinery. ;-) See: http://github.com/lawrencepit/machinery

One of the (perhaps not so obvious) main feature of that little gem is that you can set up plain ruby objects (and hence also objects created with Machinist, which is what I'm doing) in a before(:all) block in a transactional manner.

However, when I use Sham to generate some random values for blueprints, and these blueprints are used in a before(:all) block, then in an example test I stumble upon duplicate values generated by Sham because in the before(:each) block it will always do a Sham.reset.

I've created a patch for Sham so that you can add the following instead in the Spec::Runner.configure block of your spec_helper.rb :

```
config.before(:all) { Sham.reset(:all) }
config.before(:before) { Sham.reset(:before) }
```

This way it will generate the same sequence of values after each reset(:before) without overlapping the values generated in the before(:all).

The patch is at:

http://github.com/lawrencepit/machinist/commit/66283fda6ce6acf2fa7f0f0203eefda69468e5c5

Cheers,
Lawrence

**Comment by notahat** [comment]
config.before(:before) isn't shown in the rspec docs. Should it before(:all) and before(:each), or is there undocumented magic?

http://rspec.info/documentation/before_and_after.html

**Comment by lawrencepit** [comment]
gr! before(:each) of course. New commit at:

http://github.com/lawrencepit/machinist/commit/75bbbfd0bd33a6199be55f87fc7e8a52923add6f
