### ISSUE TITLE
Transactional fixtures not working with cucumber 8.3 and machinist2.beta2

### ISSUE THREAD

**Issue by thedeeno** [notahat/machinist#40]
I'm not completely sure why, but with machinist2 I need to disable transactional fixtures to get cucumber running repeatably. If I don't do this the database isn't properly cleaned and my scenarios fail because of duplicate records. 

As understand, it should be possible to use the transaction strategy with machinist2. I'm not sure what's going on behind the covers to prevent the transactions from encapsulating all the work.

Any thoughts as to why? I don't know what information would be helpful so I won't clog this up with stuff you don't ask for.

**Comment by thedeeno** [comment]
I think it has something to do with lib/machinist/shop.rb ln 43. Why do you need to do anything outside the transaction?

**Comment by notahat** [comment]
It's part of the object caching mechanism. See http://wiki.github.com/notahat/machinist/object-caching

The problem is that Cucumber doesn't reset the database before test runs. I'm still figuring out what to do about this.

**Comment by thedeeno** [comment]
Well to reset cucumber's database after a test run a global hook can be added to the cucumber's `env.rb`. Something like this works:

```
at_exit do
  DatabaseCleaner.clean
end
```

Should machinist automatically add something like this when it's loaded? Or would you consider that out of scope? If caching is supposed to be set at a the 'suite' level, the automatic inclusion could check to see that it's enabled before even adding the hook.

**Comment by notahat** [comment]
Not sure. I'm still thinking about it.

**Comment by thedeeno** [comment]
well, another solution might be to disable caching by default. Though I'm not totally sure of this either.

Does the mainline case benefit from the caching? Or is it only for large setups?

**Comment by thedeeno** [comment]
Regardless, if you want to add the hook I'd take that on if needed.

**Comment by sobrinho** [comment]
Object caching was removed, this issue can be closed to ;)

**Comment by notahat** [comment]
What sobrinho said. :)
