### ISSUE TITLE
blueprint for mongoid embeds_many association

### ISSUE THREAD

**Issue by krishna-shilpakar** [notahat/machinist#41]
I am using machinist and mongoid. How can I generate blueprint for embeds_many association. Mongoid embeds_many association embeds the hash of array. So I just started like this:

<pre>
 User.blueprint do
   address { :address1 => "address", :address2 => 'next address'}
 end
</pre>

Is this right way of defining? I don't feel good in this way.

**Comment by notahat** [comment]
You should take this to the mailing list.
