### ISSUE TITLE
Problems with object caching

### ISSUE THREAD

**Issue by hashmal** [notahat/machinist#47]
It would be nice to have object caching disabled by default, at least as long as it is "experimental". It was giving me a lot of false positives everywhere (for example, the cache doesn't seem to reset between test runs, am I wrong?) until I figured how to disable it.

Except that, Machinist is indeed a lot funnier than fixtures :)

**Comment by inspire22** [comment]
I'm having issues with something like this too.  I'm not sure if its the same thing so I'll add my own ticket for now.

How did you disable the caching?

**Comment by hashmal** [comment]
Add this In config/environments/test.rb

```
require 'machinist'

Machinist.configure do |config|
  config.cache_objects = false
end
```

This will result in slower tests, but that's better that erroneous tests!

**Comment by joseph-ravenwolfe** [comment]
Thanks hashmal that fixed it for me. I spent hours trying to figure out what was going on.

In a Cucumber step I had:

```
Given /^there are (\d+) users$/ do |num|
    num.to_i.times{ User.make! }
    puts "Number of Users: #{User.count}"
end
```

This would puts "Number of Users: 0" during the scenario. Running console in test afterward would show the users actually in the database. Needless to say, that meant DatabaseCleaner truncation wasn't working as well. Turning off object caching solved all of these peculiarities for me.

**Comment by sobrinho** [comment]
And again, object caching was removed :)

**Comment by notahat** [comment]
What sobrinho said.
