### ISSUE TITLE
strange issue with validation failures in has_many.make!

### ISSUE THREAD

**Issue by inspire22** [notahat/machinist#48]
Topics have many comments
Topic.first.comments.make! => validation error 'topic can't be blank'
c = Topic.first.comments.make
c.save => true

Callback at validation error:

ActiveRecord::RecordInvalid: Validation failed: Topic can't be blank
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/activerecord-3.0.0.beta4/lib/active_record/validations.rb:46:in `save!'
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/active_record/blueprint.rb:35:in`value'
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/active_record/blueprint.rb:35:in `outside_transaction'
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/shop.rb:43:in`buy'
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/machinable.rb:55:in `make!'
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/machinable.rb:94:in`decode_args_to_make'
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/machinist-2.0.0.beta2/lib/machinist/machinable.rb:53:in `make!'
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/activerecord-3.0.0.beta4/lib/active_record/associations/association_collection.rb:421:in`send'
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/activerecord-3.0.0.beta4/lib/active_record/associations/association_collection.rb:421:in `method_missing'
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/activerecord-3.0.0.beta4/lib/active_record/base.rb:1167:in`with_scope'
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/activerecord-3.0.0.beta4/lib/active_record/associations/association_proxy.rb:201:in `send'
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/activerecord-3.0.0.beta4/lib/active_record/associations/association_proxy.rb:201:in`with_scope'
    from /Users/kevin/.rvm/gems/ree-1.8.7-2010.02/gems/activerecord-3.0.0.beta4/lib/active_record/associations/association_collection.rb:417:in `method_missing'
    from (irb):1

Thanks!

**Comment by notahat** [comment]
Not nearly enough info for me to track this down. I need some runnable code.
