### ISSUE TITLE
.make! calls in before :all get mysteriously changed

### ISSUE THREAD

**Issue by inspire22** [notahat/machinist#49]
before(:all) do
    @u = User.make!
end

describe "blah" do
it "tests" do
puts "old u.id is #{@u.id}"
u2 = User.make!
puts "u.id is now #{@u.id}"
end
end

somehow manages to change my @u's id from 1 to 2 just by calling .make! on another row.  I have no idea how this is possible, but it must be related to some weird haxorness.

Moving the .make! call into a before :each fixes the problem, but then the tests take twice as long to run (even though its only making 4 simple rows before each of 30 tests).  

Innodb.  But when I check the logs there are "commits" all over, so clearly using transactions isn't working as expected?

**Comment by notahat** [comment]
You should never do database stuff in a before(:all). Transactional fixtures won't clean this stuff up, and you end up leaving data lying around after your test finishes.

**Comment by notahat** [comment]
You should never do database stuff in a before(:all). Transactional fixtures won't clean this stuff up, and you end up leaving data lying around after your test finishes.
