### ISSUE TITLE
"Save failed" with DataMapper

### ISSUE THREAD

**Issue by lwouis** [notahat/machinist#50]
I followed all the information I was able to find, but still, with this minimal code:

```
require "machinist/data_mapper"

Post.blueprint do
    title "machinist"
    body "machinist works!"
end

post = Post.make
```

I got a frustrating error:

```
RuntimeError: Save failed
```

Also, when I try to use 'make!' as indicated in the docs, I get:

```
NoMethodError: undefined method `make!' for Post:Class
```

**Comment by notahat** [comment]
Can you tar up your minimal project and post it to the mailing list? Without some runnable code, it's hard for me to say what the problem might be.

**Comment by lwouis** [comment]
Ok, I'm sorry, it was a legimit "Save failed" because of a validation. I thought it was Machinist's fault because of the way the error was display but it's not.

That being said, I think I still have a legitimate error caused by Machinist. That is, I can't use relationship between Tag and Post (blog application). When I add a Tags(3) attribute to the Post blueprint, I get an error 'Stack level too high".

**Comment by notahat** [comment]
Again, I can't help you without some runnable code, and you should take this sort of problem to the mailing list: http://groups.google.com/group/machinist-users

This issue tracker is for bug reports, not support.

**Comment by lwouis** [comment]
As my initial post showed, I thought that with a minimal setup, Machinist was presenting a bug. I made a error of judgement as it seems to be all on my part. I'm sorry for the inconvenience though, I will go the to boards first, as you advise, if I get another problematic behavior.
