### ISSUE TITLE
accepts_nested_attributes_for

### ISSUE THREAD

**Issue by 23inhouse** [notahat/machinist#51]
I love using blueprints!

In my Foo model, I've started adding accepts_nested_attributes_for :bar, :bar, ...
So I can create complex nested blueprints that have all the important attributes.

```
    Foo.blueprint(:custom) do
      name "custom"
      bars_attributes { [Bar.plan(:custom1), Bar.plan(:custom2)] }
      baz_attributes { Baz.plan(:custom) }
    end
```

It would be great if all the Model associations automatically had accepts_nested_attributes_for set for all their associations (in blueprinting phase only, like mass-assignment override).

I tried using the other association method in the docs, but i find accepts_nested_attributes_for to be more flexible.

Thanks for the great plugin.

**Comment by notahat** [comment]
Enabling accepts_nested_attributes_for changes the behaviour of your code, so doing it just in test mode would be a bad idea. You want the code to behave the same way in test and in production.

**Comment by 23inhouse** [comment]
Yes, i agree.  I was hoping the changes could be isolated to the creation of blueprints only.
I wasn't really sure how to do it, but i was hoping one of these methods might work:
- the classes could be modified during the calls to <code>plan</code> and/or <code>make</code>, then returned to their original state, which might be slow.
  -  or the model classes could be duplicated and all their association_attributes setter methods could be removed and recreated with clean versions, one for each association.

**Comment by notahat** [comment]
I'm not really convinced. Feel free to fork and give it a go though!
