### ISSUE TITLE
Is Sham.reset deprecated?

### ISSUE THREAD

**Issue by millisami** [notahat/machinist#52]
Hi, I'm using beta 2.2 and my test database is not getting cleared.
I can't use the `Before { Sham.reset }` in env.rb for cucumber, it blows with the following error:
    uninitialized constant Sham (NameError)

Is `Sham.reset` is deprecated or how to reset the test db each time??

**Comment by notahat** [comment]
Sham doesn't exist in Machinist 2. See http://wiki.github.com/notahat/machinist/machinist-2

Please take issues like this to the mailing list: http://groups.google.com/group/machinist-users

**Comment by millisami** [comment]
Thanks.
