### ISSUE TITLE
`#make!` fails mysteriously unless it is the first DB action to occur in the test suite

### ISSUE THREAD

**Issue by bjeanes** [notahat/machinist#56]
This is reaaaaally peculiar and I can't seem to get around it. Let the code speak:

```
# Running...
p User.make!
p User.all

# Results in ...
#<User id: 1, email: "rachel_leuschke@douglasbeer.name", encrypted_password: "075f01447f9b029b1ee3ef77f0b47179774a5046a5d696280c2...", password_salt: "_QBwGhaeJe2ijc55WS9q", authentication_token: nil, reset_password_token: nil, remember_token: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: "2010-09-18 00:06:50", updated_at: "2010-09-18 00:06:50">
[#<User id: 1, email: "rachel_leuschke@douglasbeer.name", encrypted_password: "075f01447f9b029b1ee3ef77f0b47179774a5046a5d696280c2...", password_salt: "_QBwGhaeJe2ijc55WS9q", authentication_token: nil, reset_password_token: nil, remember_token: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: "2010-09-18 00:06:50", updated_at: "2010-09-18 00:06:50">]

# And then a second run with any other DB interaction (find, insert, update -- doesn't matter)

# Running...
p User.all   # this prevents `User.make!` from working
p User.make!
p User.make!
p User.make!
p User.all

[]
#<User id: 1, email: "jordane@jacobs.com", encrypted_password: "e91a497e69ba78c5b606d06d49062f03d0d075b52371d373ca9...", password_salt: "wBYuMquZETYM-QyNGqf7", authentication_token: nil, reset_password_token: nil, remember_token: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: "2010-09-18 00:11:19", updated_at: "2010-09-18 00:11:19">
#<User id: 2, email: "evan@okon.ca", encrypted_password: "7c2884f19e55e2334b95984f211f50e241b3fc3e8d385e0c2e2...", password_salt: "dIvYK2Xy0IUBME5DO8J4", authentication_token: nil, reset_password_token: nil, remember_token: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: "2010-09-18 00:11:19", updated_at: "2010-09-18 00:11:19">
#<User id: 3, email: "cortney.luettgen@barrowsmueller.ca", encrypted_password: "a1531ec3605390c03a3c2cce16bb930c87ecd009cf21319ec54...", password_salt: "T_-n-bafzbhwpW9uRo-s", authentication_token: nil, reset_password_token: nil, remember_token: nil, remember_created_at: nil, sign_in_count: 0, current_sign_in_at: nil, last_sign_in_at: nil, current_sign_in_ip: nil, last_sign_in_ip: nil, created_at: "2010-09-18 00:11:19", updated_at: "2010-09-18 00:11:19">
[]
```

Those chunks of code were run inside a cucumber step. I found the issue because the step only passed if it was the _first_ one that was executed in the scenario. If I so much as hit the home page, the `User` would not be created properly.

Interestingly, note that it is actually incrementing the User ID and that `User.make!` returns the object successfully, thinking that it created the object in the db correctly. Furthermore, if I put `ActiveRecord::Base.logger = Logger.new(STDOUT)` before the `User.make!` calls, I can see that it does actually run `INSERT` queries in a transaction and that even `COMMIT` is called. Yet somehow, the rows do not end up in the database.

**Comment by notahat** [comment]
The short answer: either a) turn off Machinist 2's caching, b) wait for the next beta which will have a different caching strategy, or c) put MySQL into read-committed mode.

The long answer:

MySQL runs with an isolation level of repeatable-read by default. That means once you've run a query once, you'll get the same results back for the same query until you commit your transaction, even if data is committed to the database in the meantime.

Machinist runs calls to make! on a separate DB connection as part of its caching approach, so what's happening here is:
1. You read all the users
2. Machinist makes a user on another connection and commits it
3. You read all the users, and MySQL enforces giving you the same result as the first time you read them

**Comment by bjeanes** [comment]
Ah of course repeatable-read. Seems obvious now. Caching disabled works like a charm so thanks a lot for the explanation :)
