### ISSUE TITLE
rake - copy - bundler

### ISSUE THREAD

**Issue by robotarmy** [notahat/machinist#57]
Hi - i a have an attributes in a rails project named 'copy'

since i started to use bundler i am getting issues with rake conflating this with
my code - since bundler both specifies dependencies and loads dependencies
i am now having this issue.

do to the way that machinist is specifying calls internally with these do block- - without namespace
the attribute 'copy' is getting conflated with 'copy' in the general namespace (also not good)- please consider this in your design - i have also raised the issue with rake, and bundler.

1194 #############################################################################
1195 # Include the FileUtils file manipulation functions in the top level module,
1196 # but mark them private so that they don't unintentionally define methods on
1197 # other objects.
1198
1199 include RakeFileUtils
1200 private(FileUtils.instance_methods(false))
1201 private(RakeFileUtils.instance_methods(false))
1202

**Comment by notahat** [comment]
In your blueprint just do:

```
MyClass.blueprint do
  self.copy { ... }
end
```
