### ISSUE TITLE
belongs_to association through virtual attribute

### ISSUE THREAD

**Issue by ghost** [notahat/machinist#6]
Basically, Machinist doesn't allow this behavior:

<pre>
Group.blueprint do
  name
  category_name
end

Category.blueprint do
  name
end
</pre>

And the model:

<pre>
class Group < ActiveRecord::Base
  belongs_to :category
  before_save :assign_category
  attr_writer :category_name

  def assign_category
    self.category = Category.find_or_create_by_name(category_name)
  end
end
</pre>

What I'm trying to do, is to let the user create a group with a given category name. It works, but when I create a group in my tests, it doesn't get a category.

Support for assigning belongs_to associations through a virtual attribute would be nice. :)

**Comment by notahat** [comment]
Looks to me like that should work just fine. Can you give me a complete failing test?

**Comment by ghost** [comment]
Test:

<pre>
class GroupsControllerTest < ActionController::TestCase
  context 'index action' do
    setup do
      3.times { Group.make }
      get :index
    end

    should_assign_to :group_categories
    # etc...
  end
end
</pre>


Error:

<pre>
  1) Error:
test: index action should assign @group_categories. (GroupsControllerTest):
ActionView::TemplateError: You have a nil object when you didn't expect it!
The error occurred while evaluating nil.name
    On line #4 of app/views/groups/index.html.erb
    
        1: <% title 'Groups' %>
        2: 
        3: <% @group_categories.each do |category, groups| %>
        4:   <h2><%= category.name %></h2>
        5:   <ul>
        6:     <% groups.each do |group| %>
        7:       <li>
    
        app/views/groups/index.html.erb:4
</pre>


Changing the setup block to this is a temporary fix:

<pre>
Group.destroy_all
Category.destroy_all
3.times { Group.create(:name => 'Group', :category_name => 'Category') }
get :index
</pre>


Unless I'm missing something, Machinist is the culprit here.

**Comment by notahat** [comment]
Ok, I can't really see what's going on from that, unless you give me code I can run. Can you write a test for Machinist that fails in a similar way?

**Comment by ghost** [comment]
I forked the repo and tried to recreate the issue in the specs:

I added this to the Comment model:

<pre>
attr_writer :author_name
before_save :assign_author

def author_name
  if @author_name
    @author_name
  else
    author.name if author
  end
end

def assign_author
  self.author = Person.find_or_create_by_name(author_name)
end
</pre>


And added this spec to active_record_spec.rb:

<pre>
it "should allow setting an association in a callback" do
  Comment.blueprint do
    author_name "John Doe"
  end
  Comment.make.author.class.should == Person
end
</pre>


I think this test replicates the circumstances fine. But the test passes. Meaning I have no idea what's wrong with my app. :(

Sorry to bother you.

**Comment by ghost** [comment]
It seems rebooting my computer made the tests pass in my app. There must have been some leftovers in the database or something, I don't know. Again, sorry to bother you.

**Comment by notahat** [comment]
Ok, I'll close the issue then.
