### ISSUE TITLE
Circular associations

### ISSUE THREAD

**Issue by leonardochen** [notahat/machinist#60]
If you define two classes in the blueprint that have associations to each other, Machinist just keep trying to create more and more instances of the objects, until the test eventually crashes. 

In smaller projects, it's fairly easy (though not always convenient) to determine a tree for dependencies and always follow that when making objects in the tests. In bigger projects, it would be nice not to worry about that.

From the example:
User.blueprint do
  name
  email
  posts(3)  <<< Add this line and you're toast
end

Post.blueprint do
  title
  author
  body
end

**Comment by notahat** [comment]
If you can work out how to solve this, I'm all ears! :)

It's very difficult to detect these circularities, and it's not clear how they should be handled anyway.

In general, you should only go through belongs_to associations in your blueprints, and you should build helper methods for constructing more complex object graphs when you need them.

**Comment by leonardochen** [comment]
Thanks Notahat.
I think just having the note you just told me on the readme would be very helpful for newcomers.

**Comment by jackdempsey** [comment]
@notahat I've come across the circular thing too, and sometimes helper methods don't feel quite right. I've taken to doing this:

``` ruby
Car.blueprint do
  passengers { [Passenger.make(car: object)] }
end

Passenger.blueprint do
  car
end
```

which seems to work fine, and I can still easily create Passengers with car supplied by Machinist. Anything wrong about this approach?
