### ISSUE TITLE
Machinist (2.0.0-beta2) forgetting blueprints between tests

### ISSUE THREAD

**Issue by sardaukar** [notahat/machinist#64]
Hello.

I'm using Machinist 2 with Rspec 2.4, Capybara 0.3.9 and Faker 0.9.4 on a Rails 3.0.3 project. So far, the only way I got Machinist to _not_ give me a NoBlueprintError is to have 

```
config.before(:each)   { load File.expand_path(File.dirname(__FILE__) + "/support/blueprints.rb") } 
```

 on spec_helper.rb, which just looks bad. If I don't do this, the blueprints are "forgotten" after the first step. I also tried Machinist.reset_before_test, to no avail.

 What can I be doing wrong? Thanks for any help.

**Comment by sardaukar** [comment]
Oh, and I only get this if config.cache_classes is turned off (false).

**Comment by dsboulder** [comment]
We experienced this also with rails 3.0.4 and rspec 2.4.0/rspecrails 2.4.1.

Only REQUEST specs seem to cause the blueprints to be forgotten, regardless of class caching being on or off (though we suspect it's a class reloading issue).

Our workaround:

  config.after :type => :request do
    load File.dirname(**FILE**) + "/support/blueprints.rb"
  end

**Comment by sardaukar** [comment]
thanks for the reply!

**Comment by ramhoj** [comment]
Thank you for the workaround! Perhaps this should be added to the readme?
