### ISSUE TITLE
Rails3 RSpec2 autotest machinist created objects are not reset

### ISSUE THREAD

**Issue by rwestgeest** [notahat/machinist#65]
Hi,

I am trying machinist. Syntax looks great! 
The problem i have is that objects created with make! aren't removed before each tests. Using rake everything works fine. Also i determined that the config.before block is calles like it should.

My config: 
Rails3 RSpec2 

in spec_helper:
Machinist.configure do |config|
  config.cache_objects = false
end

RSpec.configure do |config|
  # Reset the Machinist cache before each spec.
  config.before(:each) {
    p "running config before" # to check wether reset_before_test is called
    Machinist.reset_before_test
  }
 # .....
end

I am at a loss. This could of course also be an autotest problem. 

Cheers Rob

**Comment by notahat** [comment]
Machinist depends on transactional fixtures to clean things up. If you don't have these enabled, any database activity will get left around at the end of your tests.
