### ISSUE TITLE
Cant't assign a stressed character to a field

### ISSUE THREAD

**Issue by tpresa** [notahat/machinist#67]
Hi,

I'm trying to test the following blueprint:

Promotion.blueprint do
  title { 'é' }
end

But I get:

C:/Ruby187/lib/ruby/gems/1.8/gems/activesupport-3.0.3/lib/active_support/depende
ncies.rb:239:in `require': xxx/spec/support/blueprints.rb:11: unterminated string meets end of fi
le (SyntaxError)
xxx/spec/support/
blueprints.rb:11: syntax error, unexpected $end, expecting '}'

When I change to 

Promotion.blueprint do
  title { 'e' }
end

Then I get the regular validation failures.

Thanks!

**Comment by notahat** [comment]
This is a Ruby string encoding issue, and has nothing to do with Machinist. Closing.
