### ISSUE TITLE
Machinist doesn't play well with model callbacks

### ISSUE THREAD

**Issue by tpresa** [notahat/machinist#69]
Hi,

I'm using the following call:

Device.make!(:device_hash => '1234')

And the blueprint is:

Device.blueprint do
  serial_no { '5678' }
end

But in the Device model I have the following before_save:

  def parse_serial_no
    self.device_hash = Digest::SHA1.hexdigest(serial_no)
  end

Which means I don't get a model with the device_hash that I wanted. Shouldn't machinist cope with this case?

**Comment by notahat** [comment]
Machinist doesn't do any special magic when constructing an object. In your example, Machinist just does:

```
device = Device.new
device.serial_no = '5678'
device.save!
```

All the normal ActiveRecord hooks are run. This is expected behaviour.
