### ISSUE TITLE
Inform people that Shams are no longer used on the Machinist 2 install wiki page

### ISSUE THREAD

**Issue by theirishpenguin** [notahat/machinist#71]
Hiya guys,

Great project. Thanks so much. Just a quick point.

Can you please update the https://github.com/notahat/machinist/wiki/Installation page to link to "What’s new in Machinist 2 page" (https://github.com/notahat/machinist/wiki/machinist-2). Especially just to let people know that Sham is no longer used. It took me a while to track down the fact that Sham is no longer.

I've put a little post up in case people run into this issue at http://www.theirishpenguin.com/2011/02/16/machinist-2-and-the-undefined-method-foo-for-shammodule-error

All the best,
Declan

**Comment by notahat** [comment]
The README now takes people upgrading from Machinist 1 to the wiki page, and that talks about replacing Sham.
