### ISSUE TITLE
Plan method in machinist 2

### ISSUE THREAD

**Issue by tbuehl** [notahat/machinist#73]
Hello

I couldn't find the plan method to get the values of a blueprint as a hash. Is it possible to include this method again or is there a workaround?

**Comment by notahat** [comment]
Nope, it's gone. People didn't find it useful in Machinist 1, and the implementation was a hack.

**Comment by tbuehl** [comment]
Ok, but I think it's usefull in controller and model tests to get a hash back and give this to Model.new(). The make method overwrites attr_accessible + I cannot test nested_attributes. It prevents me from using machinist 2.

**Comment by notahat** [comment]
One of the upcoming features in Machinist 2 will address this. You'll be able to provide different strategies for constructing objects, including passing the attributes to new rather than use accessors. See the strategies branch if you want an early look.

**Comment by tbuehl** [comment]
Ok, thank you!

**Comment by TylerRick** [comment]
I found the plan method useful in machinist 1.

Can the strategy that passes the attributes to new be used to get the hash of attributes itself?

I've tried using `User.make.attributes` but in the case of a Devise-based User model, at least, the `password` attribute (virtual attribute, apparently) that I have specified in my User.blueprint is not in the attributes hash **after** the User object is built (only the `encrypted_password attribute` is available in attributes), so I can't use that `attributes` hash to build another user.

It seems like the `plan` method would be very helpful for building association objects (at least until `"There’s no make method on ActiveRecord associations (yet)".veracity == false`). That's what I'd like to use it for anyway. (I have a custom associated user builder called `create_user`, so I a need hash to test it...)

**Comment by TylerRick** [comment]
I can work around this, though, it's just kind of ugly... :)

```
  @user = @invitation.create_user(
    User.make.attributes.slice('first_name', 'last_name', 'email').merge(
      :password => 'testtest'
    )
  )
```

**Comment by jeffshantz** [comment]
I think a vital method was removed here.  I use this all the time, e.g.

before(:all) do
   @attrs = User.plan
end

it "should not be valid with a first name longer than 25 characters"
   user = User.new(@attrs.merge(first_name: "a" \* 26))
   user.should_not be_valid
end

As @TylerRick pointed out, using User.make.attributes does not play nicely with Devise.

**Comment by notahat** [comment]
Your example would be simpler like this:

```
it "should not be valid with a first name longer than 25 characters"
  user = User.make(first_name: "a" * 26)
  user.should_not be_valid
end
```

Is there some reason that won't work for you?

**Comment by iwakura** [comment]
Here is a monkey patch for plan method,
but it works only for simple objects (foreign keys and associations are missing).

``` ruby

module Machinist
  class Lathe
    public :attribute_assigned?
  end

  class Blueprint
    def plan(attributes = {})
      lathe = lathe_class.new(@klass, new_serial_number, attributes)

      lathe.instance_eval(&@block)
      each_ancestor {|blueprint| lathe.instance_eval(&blueprint.block) }

      attributes = lathe.object.attributes
      attributes.delete_if { |key, val| !lathe.attribute_assigned? key }
      attributes
    end
  end

  module Machinable
    def plan(*args)
      decode_args_to_make(*args) do |blueprint, attributes|
        blueprint.plan(attributes)
      end
    end
  end
end

```
