### ISSUE TITLE
rspec 2.6.0 breaks blueprints...

### ISSUE THREAD

**Issue by hammackj** [notahat/machinist#78]
I have several blueprints like this:

Item.blueprint do
    port { Sham.port }
    host { Host.make }
    svc_name { Sham.svc }
    severity { 0 }
    plugin { Plugin.make }
end

They all break on the host { Host.make } and plugin { Plugin.make } lines, these methods dont seem to be called with rspec 2.6.0, works fine with 2.5.0.

Thanks!

**Comment by cicloon** [comment]
Im having the same problem, is there any way to bypass this ?

**Comment by notahat** [comment]
Works fine for me with RSpec 2.8 and Machinist 2.

If you're still having the problem, give me some runnable code that demonstrates it.
