### ISSUE TITLE
make fails when no master blueprint exists

### ISSUE THREAD

**Issue by akzhan** [notahat/machinist#8]
make fails when no master blueprint exists.

I used named blueprints and doesn't require the master one. But Machinist does :(

**Comment by notahat** [comment]
That's deliberate behaviour. Allowing named blueprints without a master leads to people using blueprints just like fixtures, which defeats the purpose. I've not yet seen a production use case for named blueprints that wasn't a lot neater with a master.

If you've got a compelling use case, by all means share some code with me and I'll re-evaluate.

**Comment by adzap** [comment]
Let them eat cake! ;-)

**Comment by botanicus** [comment]
OMG, in this case it would be good at least provide a reasonable error message & emphases it in documentation, so people like me don't waste the whole day looking where the fucking error is :/

Not mention I'm not sure if it's reasonable solution and even if so, then I'm not sure if it's good idea to do the decision instead of the user. But whatever.

**Comment by botanicus** [comment]
And alright, if you want to see an example, check this: http://pastie.org/717640 I need to be sure I'm picking the right one. Or when I create User.blueprint(:admin), then I really want to explicitly specify that this is an admin user, not just an user which I can define later or never.

**Comment by notahat** [comment]
Botanicus: I don't understand what you're asking.

"No blueprint for class ..." seems like a pretty clear error message to me.

I'm not sure what your pastie is supposed to show either.

What's the behaviour you expect, and what behaviour are you seeing?

**Comment by botanicus** [comment]
No, because I had blueprint, but it was named blueprint and I hadn't the master one, so I would expect something like "you have to define unnamed blueprint before you can define named ones".
