### ISSUE TITLE
link weirdness: wrong number of arguments (1 for 2)

### ISSUE THREAD

**Issue by ramontayag** [notahat/machinist#86]
Anyone come across `link` weirdness with Machinist (pre Rails 3.1)?

I have plan like this:

```
MenuItem.blueprint do
  link
end
```

But when I call `MenuItem.make` I get this error:

`wrong number of arguments (1 for 2)`

When I remove `link` it starts to work fine. Machinist also works fine with other fields.

**Comment by ramontayag** [comment]
I made a new app, and tried it separately. It works. So it's not Machinist - it's some weirdness I gotta figure out.

**Comment by notahat** [comment]
I'm betting you define a global "link" method somewhere. Try "self.link" in the blueprint, and see if that works.

**Comment by ramontayag** [comment]
Perhaps. I ended up avoiding it altogether by renaming it to `url`. When searching for the cause of it, I saw that [it's a reserved word](http://latheesh.com/2010/02/02/rails-reserved-words/) anyway. Thanks!

**Comment by pat** [comment]
I think `link` is a method inserted into the global scope from Rake.

**Comment by vertis** [comment]
@notahat's suggestion, to use 'self.link', works well as a workaround
