### ISSUE TITLE
Should be able to set a known seed value

### ISSUE THREAD

**Issue by adamsalter** [notahat/machinist#9]
As per discussion here:

http://github.com/notahat/machinist/issues#issue/7

This is related to the seed value that machinist sets...

Setting the random seed has several effects...

a) you can get issues like above where it seems the other library resets the seed before generating... meaning that machinist sets it back and you always get the same value from `rand`

b) If you use Faker or other library, you will always get the same values as every other person using Faker... potentially a security flaw since rand is no longer random...

My suggestions would be:
- have faker increment the seed every time it resets it... so the seed is (1) first time, (2) second time, not just (1) every time. Thereby fixing above behaviour.
- have machinist use a rails constant (if available), so that the randomness is the same for that project, but not _every_ rails project. (I was thinking `ActionController::Base.session[:secret]`)
- have an option to turn off resetting the seed, so all data from machinist is truely random.

A couple of examples:

```
Machinist.sham_seed = "abc"
Machinist.sham_seed = ActionController::Base.session[:secret]
#turn on true randomness
Machinist.sham_seed = false
```

**Comment by notahat** [comment]
It's not clear to me from this, or from the discussion on issue 7, what problem you're trying to solve.

> a) you can get issues like this where it seems the other library resets the seed before generating... meaning that machinist sets it back and you always get the same value from rand

No, Sham re-seeds the random number generator when it's done, so you'll always get random values from rand inside your app.

> b) If you use Faker or other library, you will always get the same values as every other person using Faker... potentially a security flaw since rand is no longer random...

Again, rand will remain random when used outside of Sham, so Faker will give you random values as usual.

Inside Sham you want consistent values. I want the tests to be run with the same data every time, and to be run with the same data on different systems.

If you want true randomness (which is a really bad idea for regular test data), there's a simple solution: don't use Sham. Sham exists precisely to ensure consistency in the data.

**Comment by adamsalter** [comment]
Hmm... interesting... I tested this before I raised this issue. With and without Sham, but still got duplicate values. Not getting that any more... Must have gotten mixed up.

Right... would it still be possible to have a way to set the seed value for Sham?

I don't like knowing that everybody who uses the suggested code in the README:

```
Sham.email { Faker::Internet.email }
```

... will have their first email as "aric.smith@kautzergoyette.name".

I think it is a form of security risk if I can easily predict what values will occur. As I said, it might seem a little far fetch, but here's an example: An Open Source application uses Sham to create initial data. Anybody can then be quite confident what values will be in that app. If there was a way to change the initial seed, every application could potentially be different. It's still repeatably random, just a different set of random to everybody else.

**Comment by notahat** [comment]
The bigger picture here is that Machinist was really designed for generating test data, not generating seed data.

I think there's a lot more to do than just allow setting the seed for Sham. For example, Machinist would have to deal sensibly with the case where a generated value clashes with an existing value in the DB.

Feel like starting a fork? :)

**Comment by adamsalter** [comment]
re: seed data. Yeah good point.

> Feel like starting a fork?

Another good point. I guess I just wanted to set the seed value because I was actually recommended to use machinist for seed data (`config/seed.rb`), but didn't actually feel confident enough about the problem domain to do it myself. Adding a seed value seemed like a quick fix.

How would you foresee machinist helping with seed data? I guess if it checked if the model was valid during #make, #plan and reran the generation if invalid it could be used in that manner... But it gets very application specific. I do have checks in my code when values conflict with those in the database. (In fact the reason I saw this whole thing as a possible issue)

```
until User.count == counts[:users]
  u = User.new
  until u.valid?
    u.attributes = User.plan
  end
  u.save!
  puts "Created user #{u.email}"
end
```

Setting the seed value means I know the data I'm getting repeatably, but obviously different from other users of same lib.

**Comment by notahat** [comment]
I haven't thought about it that deeply. Your description sounds relatively sensible.

Re-running the make if validations fail is a little clunky, and could be error prone, but I'm not sure how else you could approach it.

Have a play around! The internals of Machinist are pretty simple, so you should be able to try out something like this without too much pain.

**Comment by adamsalter** [comment]
Will do. Might be a week or two though.

**Comment by notahat** [comment]
Closing this for now, but I'm sure we'll revisit the topic.

**Comment by adamsalter** [comment]
Here's my attempt. Needed (wanted) to use my machinist stuff for seeds.

http://github.com/adamsalter/machinist/commit/143c5462d93d2e8612471e86c8e21d64fd0ff734

**Comment by adamsalter** [comment]
One failing test. Not sure it's related to my change though (ruby 1.9.1p243):

```
1)
ArgumentError in 'Machinist ActiveRecord adapter make method should allow creating an object through a has_many association'
Anonymous modules have no name to be referenced by
/Users/adam/.gem/ruby/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:585:in `to_constant_name'
/Users/adam/.gem/ruby/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:391:in `qualified_name_for'
/Users/adam/.gem/ruby/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:104:in `rescue in const_missing'
/Users/adam/.gem/ruby/1.9.1/gems/activesupport-2.3.4/lib/active_support/dependencies.rb:94:in `const_missing'
/Users/adam/dev/plugins/machinist/spec/active_record_spec.rb:69:in `block (5 levels) in <module:MachinistActiveRecordSpecs>'
/Users/adam/dev/plugins/machinist/spec/active_record_spec.rb:69:in `block (4 levels) in <module:MachinistActiveRecordSpecs>'
/Users/adam/dev/plugins/machinist/spec/active_record_spec.rb:72:in `block (3 levels) in <module:MachinistActiveRecordSpecs>'
/opt/local/lib/ruby1.9/1.9.1/timeout.rb:44:in `timeout'
```
