### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by trivektor** [notahat/machinist#95]
I got the following error when installing machinist

/Users/trivuong/.rvm/gems/ruby-1.9.2-p290/gems/thor-0.14.6/lib/thor/actions/inject_into_file.rb:99:in `binread': No such file or directory - /Users/trivuong/Projects/strawberries/spec/spec_helper.rb (Errno::ENOENT)

I'm using Rails 3.1 rc4

**Comment by notahat** [comment]
That looks like an issue with somewhere between thor and rspec. Nothing to do with Machinist. I imagine you'll get the sam error trying to run any generators.
