### ISSUE TITLE
Admin::User.blueprint doesn't work 

### ISSUE THREAD

**Issue by loganayakip** [notahat/machinist#97]
I have a model 'User' which is placed inside the directory called  'admin'. I have to create a blueprint data for this mode in order to be using the same for functional testing.  when I give Admin::User.blueprint, it throws "undefined method `blueprint' for Admin::User:Class (NoMethodError)". Can anyone please help me out on this to get it working?

**Comment by notahat** [comment]
You need to provide some code I can run to duplicate the issue.

**Comment by loganayakip** [comment]
The following is the code snippet which I was unable to get it run successfully .
ServiceListener::Listener.blueprint do
  name                          {Faker::Name.name}
  group                         {Faker::Name.name}
end

Please help me out to resolve the issue.

**Comment by notahat** [comment]
Sorry, but it needs to be code I can run, meaning I need a project with a failing test. I've got a dozen examples like that in my codebase which work just fine, so I can't tell what the problem is without more context.
