### ISSUE TITLE
Machinist make! generate a model that raise ActiveRecord::RecordNotFound on reload

### ISSUE THREAD

**Issue by phuong-nguyen** [notahat/machinist#98]
I'm running Rspec2 + Machinist 2.0.0.beta2 (with transactional fixtures enabled).
I then defined a blueprint for Venue model class.
When I call Venue.make!, Machinist returns a Venue model with an id assigned. But when I call reload on that model, ActiveRecord::RecordNotFound exception is raised.
Dig into the Machinist code, we find these lines:

[40, 49] in gems/machinist-2.0.0.beta2/lib/machinist/shop.rb
...
  shelf = @back_room[blueprint, attributes]
  if shelf.empty?
    object = blueprint.outside_transaction { blueprint.make!(attributes) }
    @warehouse[blueprint, attributes] << blueprint.box(object)
    object
  else
    blueprint.unbox(shelf.shift)
  end
end

Could that blueprint.outside_transaction be causing problem?

**Comment by notahat** [comment]
Yes. Turn off caching. See https://github.com/notahat/machinist/wiki/Object-Caching
